# Generated by Django 3.1.2 on 2020-11-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
        ('lmn', '0003_auto_20201127_1708'),
    ]

    operations = [
    ]
