# Generated by Django 3.1.3 on 2020-11-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_merge_20201129_2127'),
        ('lmn', '0002_note_rating'),
    ]

    operations = [
    ]
