# Generated by Django 3.1.2 on 2020-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20201130_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
