# Generated by Django 3.1.2 on 2020-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20201127_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
