# Generated by Django 3.1.2 on 2020-12-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20201127_1731'),
        ('lmn', '0005_auto_20201130_1552'),
    ]

    operations = [
    ]
