# Generated by Django 3.1.2 on 2020-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_venue_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default=1607105675.992741, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(default=1607105691.073339, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
