# Generated by Django 3.1.2 on 2020-12-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_merge_20201205_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
