# Generated by Django 3.1.2 on 2020-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0008_auto_20201204_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
